// Data Use Terms page for PIXI Center — public-facing.
// Content sourced from "CIRP-DUA.md" (the CIRP Resource Sharing Policy, provided
// by the PIXI Center team).
// Uses tokens from ../colors_and_type.css and primitives from ../home/ui.jsx,
// with the same TopNav/Footer as the other public pages (../home/site-chrome.jsx).

const proseP = {
  margin: "0 0 20px",
  fontFamily: "var(--font-sans)",
  fontSize: 16,
  lineHeight: 1.65,
  color: "var(--fg-2)",
};

const proseLi = {
  marginBottom: 14,
};

const DataUseTermsHeader = () => (
  <section style={{
    padding: "72px 40px 8px",
    maxWidth: 760, margin: "0 auto",
  }}>
    <Eyebrow mono>Data sharing</Eyebrow>
    <h1 style={{
      margin: "14px 0 22px",
      fontFamily: "var(--font-display)",
      fontSize: 44, fontWeight: 600, letterSpacing: "-0.02em", lineHeight: 1.1,
      color: "var(--fg-1)",
    }}>
      Data Use Terms
    </h1>
    <h2 style={{
      margin: "0 0 20px",
      fontFamily: "var(--font-display)",
      fontSize: 20, fontWeight: 600, letterSpacing: "-0.01em",
      color: "var(--fg-1)",
    }}>
      CIRP Resource Sharing Policy
    </h2>
  </section>
);

const Policy = () => (
  <section style={{ padding: "8px 40px 56px", maxWidth: 760, margin: "0 auto" }}>
    <p style={proseP}>
      The Co-clinical Imaging Research Resource Program Network (CIRP) is organized to
      advance the practice of precision medicine by establishing consensus-based best
      practices for co-clinical imaging and developing optimized state-of-the-art
      translational quantitative imaging methodologies to enable disease detection, risk
      stratification, and assessment/prediction of response to therapy. A critical path to
      achieve the goals of the CIRP is the dissemination of research results and resources
      to the scientific community.
    </p>
    <p style={proseP}>
      A CIRP Resource is any collection of information, including data, protocols, or
      tools, that is generated by CIRP members. This can include single sites or multiple
      sites. This document represents the CIRP's resource sharing policy. The spirit of
      this policy is one of collaboration and flexibility and to introduce a minimal
      amount of oversight and/or committee work to CIRP members. The CIRP is committed to
      providing commercial and academic investigators an opportunity to access data
      collected as part of CIRP studies.
    </p>
    <p style={{ ...proseP, marginBottom: 0 }}>
      All CIRP members, associate/affiliate members, external collaborators, companies,
      and "data users" should be made aware of the guiding principles of the CIRP Sharing
      Policy.
    </p>
  </section>
);

const DataUseTermsList = () => (
  <section style={{
    padding: "56px 40px 56px", maxWidth: 760, margin: "0 auto",
    borderTop: "1px solid var(--border-subtle)",
  }}>
    <h2 style={{
      margin: "48px 0 20px",
      fontFamily: "var(--font-display)",
      fontSize: 28, fontWeight: 600, letterSpacing: "-0.01em",
      color: "var(--fg-1)",
    }}>
      Data use terms
    </h2>
    <p style={proseP}>Data use terms are as follows:</p>
    <ul style={{ ...proseP, paddingLeft: 20, margin: "0 0 20px" }}>
      <li style={proseLi}>
        Acknowledge the Washington University Co-Clinical Imaging Research Resource
        (WU-C2IR2), including grant U24CA209837, when publicly presenting any results or
        algorithms that benefitted from their use.
      </li>
      <li style={proseLi}>
        Papers, book chapters, books, posters, oral presentations, and all other printed
        and digital presentations of results derived from CIRP data should acknowledge
        the site where the data originated and the Washington University Co-Clinical
        Imaging Research Resource (WU-C2IR2), including grant U24CA209837.
      </li>
      <li style={proseLi}>
        If a resource (data, algorithm, phantom, etc.) has a publication associated with
        it, all printed or digital presentations should cite the associated publication.
      </li>
      <li style={{ marginBottom: 0 }}>
        Failure to abide by these data use terms may result in termination of your right
        to access and use the CIRP member data.
      </li>
    </ul>
  </section>
);

const GuidingPrinciples = () => (
  <section style={{ padding: "0 40px 80px", maxWidth: 760, margin: "0 auto" }}>
    <h2 style={{
      margin: "0 0 20px",
      fontFamily: "var(--font-display)",
      fontSize: 28, fontWeight: 600, letterSpacing: "-0.01em",
      color: "var(--fg-1)",
    }}>
      Guiding principles
    </h2>
    <p style={proseP}>The guiding principles are as follows:</p>
    <ul style={{ ...proseP, paddingLeft: 20, margin: 0 }}>
      <li style={proseLi}>
        Fairness, collegiality, and cooperation in the joint pursuit of scientific
        advancement. The CIRP encourages use of resources generated within the CIRP
        network consistent with these goals.
      </li>
      <li style={proseLi}>
        The CIRP has a responsibility to ensure that the use of CIRP Resource is ethical
        and scientifically sound.
      </li>
      <li style={proseLi}>
        Data will be shared in a manner that allows good use to be made of them. This
        includes, for example, proper documentation, indexing, or curation/vetting of
        data where appropriate. Appropriate attribution and acknowledgement for CIRP
        Resources will be provided.
      </li>
      <li style={proseLi}>
        CIRP data and tools typically will not be released to individuals or companies
        prior to the publication of the project's primary aim manuscript.
      </li>
      <li style={proseLi}>
        Data sharing will not burden the CIRP's resources such as to impede its ability
        to pursue its primary research.
      </li>
      <li style={proseLi}>
        Investigators interested in asking research questions based on data collected as
        part of CIRP projects are encouraged to do so as a collaborative effort within
        the CIRP structure and the CIRP site which originated the data.
      </li>
      <li style={{ marginBottom: 0 }}>
        Investigators interested in using CIRP data must agree to adhere to the CIRP
        publication policy.
      </li>
    </ul>
  </section>
);

const DataUseTermsPage = () => (
  <div className="pixi-root" data-screen-label="PIXI Center data use terms">
    <TopNav />
    <DataUseTermsHeader />
    <Policy />
    <DataUseTermsList />
    <GuidingPrinciples />
    <Footer />
  </div>
);

ReactDOM.createRoot(document.getElementById("root")).render(<DataUseTermsPage />);
